#!/usr/bin/env python3

from src.Core import Core

if __name__ == '__main__':
    try:
        mecagenius = Core()
        while True:
            mecagenius.run()
    except KeyboardInterrupt:
        mecagenius.releas()
